name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install rust nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt clippy rust-src llvm-tools
      - name: Clippy
        run: cargo clippy --no-deps
      - name: Check formatting
        run: cargo fmt --check
      - name: Build
        run: cargo build --verbose
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install rust nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt clippy rust-src llvm-tools

      - name: Install wasm-pack
        run: npm install -g wasm-pack

      - name: Build liblisa-wasm
        run: cd liblisa-wasm && wasm-pack build --target web

      - name: Install NPM packages
        run: cd site && npm install

      - name: Build Vue project
        run: cd site && npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: liblisa-web
          directory: site/dist/